apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: UG9zdGdyZXNfREI= # Base64 encoded database name
  POSTGRES_USER: YWRtaW4= # Base64 encoded username
  POSTGRES_PASSWORD: QDlhU3E4eks5VklEJA== # Base64 encoded password
