apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: capability
                    operator: In
                    values:
                      - multi-purpose
      containers:
        - name: payment-service
          image: ubuntu:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo processing payments; sleep 10;done"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"