apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: product-catalog:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000