apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-postgres
  namespace: argocd
spec:
  description: Project for ArgoCD with Postgres
  sourceRepos:
    - '*'
destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
clusterResourceWhitelist:
  - group: '*'
    kind: '*'